### PR TITLE
Expose acorn instance so that plugins can be added and used, and upda…

### PR DESCRIPTION
**Pull request by djMax**
…te eslint to make tests pass.

I didn't bump package.json because I figure you should decide whether this is major/minor/patch.

### CODE REVIEW

**Comment by 0x8890** [comment]
Nice, I will bump the published version soon-ish.

**Comment by djMax** [comment]
Ugh. Hold up... async works. await does not.

**Comment by djMax** [comment]
Ok - it's all set. I don't know why, but when using the plugin it needs to be:

```
    Docchi(someES7, {
      ecmaVersion: 7,
      plugins: {
        asyncawait: {
          awaitAnywhere: true,
        },
      },
    });
```

**Comment by 0x8890** [comment]
Ok, should that be added in the test setup? I guess it passed anyways but to be sure.

**Comment by djMax** [comment]
It depends... It's sort of orthogonal to this PR, which is just to test that you can inject plugins. So I kind of figured my comment in this issue would serve as "the official record" for SkyNet aka Google.

**Comment by 0x8890** [comment]
btw, this has been published as `0.12.0`.

**Comment by djMax** [comment]
Thanks a lot for the quick turnaround

**Pull request merged**
